language: python
matrix:
  include:
  - python: '3.4'
    env: TOXENV=py34
  - python: '3.5'
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.6'
    env: TOXENV=lint
install:
- pip install tox codecov
script:
- tox -e $TOXENV
after_success:
- codecov
deploy:
  provider: pypi
  user: test_seunuk
  password:
    secure: m/kpf1drGhKMY2sm/GVJ/OjCyeXPns7r0rbI/wf3fxPSP8h+3kGobxyEeKxEor/2gmEyv4m1fk8Fj212undWukeoX8gjAZAyaz7tYshPPWF5n1wsCsiwe9nTj7vDlLc6J+eULkkVDbyJ6d+yalKZ1A3nWdPts7ktO2gTiCY/WwYDrJLPa3kY4nT8n3d8iJNK08GolKH8f4P3P8NuXToUEn9xEmQYOMYY81OO4aJ61/3Aq+8i9ljVVMmge80+fzcg6XNBYxk7oFn6aDowb8zNvc/1aL6ZOraBKhSUqb2GfGrDzCc1v0+qKIV29WBoCEOjB0Snm21xMFbFocDlXz0sc4j7ZTPUV5pMaEQOJfG/qc0XPjXyjB++fdGPKsd3F0OGspD0Zg14T93f+KQyCXCM1STYGd2FKzXICGeDckjZjyEkzfaxqqDWJ0XwrQpxUEC23hK6Op/DqHE16pSqp7ulXZiFnJQNEwmJMUKyb3eHSBgi0r9YyaTvkJS0qFLGw9Lu8bfi+uMT9+DM8pUaXPuTRplz9P/AGvkN/4IwhxYGsr7t0vN9jNbCtJB5k9/KF9ooYx5Lwvm4N0UV3q+slz32TBkJ9y+J4CW1Riq18kUSI0vlyDM2chIGFwFRX9mENyRCFB0/PviZBdS4GFreQRAj7QEMrCzhWn6KJGlNt782RPo=
  on:
    tags: true
  distributions: sdist bdist_wheel
